@url=http://localhost:8080/user/

POST {{url}}/chattingUsers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ilhhc2FuYm95IiwibGFzdG5hbWUiOiJBZGJ1cmFzdWxvdiIsInBob25lTnVtYmVyIjoiOTk4OTkxNzg4NDczIiwicm9sZSI6InVzZXIiLCJsYXN0TWVzc2FnZSI6bnVsbCwibGFzdE1lc3NhZ2VJRCI6bnVsbCwibWVzc2FnZXMiOltdLCJjb25uZWN0ZWRDb3Vyc2VzIjpbXSwiY29ubmVjdGVkQ2hhdHMiOltdLCJpYXQiOjE2Nzk4MTE5NjJ9.GwcbwNwZ3K6Cf7y0odDfCom2ApO1wdTxRYQYaN_1Sb4
Content-Type: application/json


{
    "chattingUsers":[1,2,3]
}
###
GET {{url}}/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ilhhc2FuYm95IiwibGFzdG5hbWUiOiJBZGJ1cmFzdWxvdiIsInBob25lTnVtYmVyIjoiOTk4OTkxNzg4NDczIiwicm9sZSI6InVzZXIiLCJsYXN0TWVzc2FnZSI6bnVsbCwibGFzdE1lc3NhZ2VJRCI6bnVsbCwibWVzc2FnZXMiOltdLCJjb25uZWN0ZWRDb3Vyc2VzIjpbXSwiY29ubmVjdGVkQ2hhdHMiOltdLCJpYXQiOjE2Nzk4MTE5NjJ9.GwcbwNwZ3K6Cf7y0odDfCom2ApO1wdTxRYQYaN_1Sb4

###
PUT {{url}}/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ilhhc2FuYm95IiwibGFzdG5hbWUiOiJBZGJ1cmFzdWxvdiIsInBob25lTnVtYmVyIjoiOTk4OTkxNzg4NDczIiwicm9sZSI6InVzZXIiLCJsYXN0TWVzc2FnZSI6bnVsbCwibGFzdE1lc3NhZ2VJRCI6bnVsbCwibWVzc2FnZXMiOltdLCJjb25uZWN0ZWRDb3Vyc2VzIjpbXSwiY29ubmVjdGVkQ2hhdHMiOltdLCJpYXQiOjE2Nzk4MTE5NjJ9.GwcbwNwZ3K6Cf7y0odDfCom2ApO1wdTxRYQYaN_1Sb4

{
    "connectedChats":[1,2,3]
}